FDA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('django.contrib.auth.urls')),
    path('', include('account.urls', namespace='account_app')),
]

account/urls.py
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.contrib import admin
from .decorators import admin_required,recep_required
from django.contrib.auth.decorators import login_required

app_name = 'account'

urlpatterns = [
    path('about/',views.about,name='about'),
    path('support/',views.support,name='support'),
    path('home/',views.home,name='home'),
    path('password/', views.change_password, name='change_password'),
    path('accounts/signup/recep/', views.RecepSignUpView.as_view(), name='recep_signup'),
    path('accounts/signup/admin/', views.AdminSignUpView.as_view(), name='admin_signup'),
    path('user/', views.user_list),
    path('dashboard/',login_required(views.dashboard),name='dash'),
    path('search/', admin_required(views.HomePageView.as_view()),name='search'),
    path('search_result/', admin_required(views.SearchResultsView.as_view()),name='search_result'),
    path('display',views.display,name = 'display'),
    path('register',views.main),
    path('search_ans/', views.get_queryset2, name='search_results') ,
    path('vhome', login_required(views.HomePage2View.as_view()), name='vhome'),
    path('download/' , views.csv_view, name='download'),
    path('team/', views.team, name='team'),
    path('not_found',views.not_found, name='not_found'),
    # path('user/<int:pk>/', views.user_detail),
    # path('display',views.display),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime
from datetime import date
from django.utils import timezone

class User(AbstractUser):
    is_recep = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    email = models.EmailField(max_length=70,blank=True ,unique=True)

class Temp(models.Model):
    uid=models.CharField(max_length=50)
    name=models.CharField(max_length=100)
    address=models.CharField(max_length=200)
    pincode=models.IntegerField(default=245101)
    purpose=models.CharField(blank=True,max_length=1000)
    gender=models.CharField(max_length=100)
    dob=models.CharField(default="05-05-1996",max_length=200)

class Visitor_perma(models.Model):
    uid=models.CharField(max_length=50)
    name=models.CharField(max_length=100)
    address=models.CharField(max_length=100)
    email=models.CharField(blank=True,max_length=70)
    phone=models.BigIntegerField()
    dob=models.CharField(default="05-05-1996",max_length=200)
    pincode=models.IntegerField(default=245101)
    purpose=models.CharField(blank=True,max_length=1000)
    whoto=models.CharField(blank=True, max_length=50)
    date=models.DateTimeField(default=timezone.now,blank=True,null=True)

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

from account.models import User,Temp,Visitor_perma
# from .models import Temp,Visitor_perma

class RecepSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    def __init__(self, *args, **kwargs):
        super(RecepSignUpForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'email','password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email", "password1", "password2")

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.is_recep = True
        user.save()
        return user

class AdminSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    def __init__(self, *args, **kwargs):
        super(AdminSignUpForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'email','password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.is_admin = True
        user.save()
        return user

class VisitorForm(forms.ModelForm):
	class Meta:
		fields = ['name', 'pincode','uid','dob','address','purpose','gender']
		model = Temp


class FilterForm(forms.ModelForm):
	class Meta:
		model = Visitor_perma
		fields = ['name', 'pincode','date','uid','dob','address','purpose','phone','email','whoto']


# class FilterForm(forms.ModelForm):
#     class Meta:
#         model = Visitor_perma
#         fields = ['name','uid','gender','address','purpose','pincode']

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import redirect, render
from django.views.generic import CreateView
from account.forms import RecepSignUpForm , AdminSignUpForm,VisitorForm , FilterForm
from account.models import User,Temp,Visitor_perma
from django.views import View
from rest_framework import mixins,status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.http import HttpResponse, JsonResponse
from rest_framework.parsers import JSONParser
import io
from account.serializer import TempSerializer
from django.http import StreamingHttpResponse
from rest_framework.renderers import JSONRenderer
from .decorators import admin_required,recep_required
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from datetime import date
import datetime
import logging
from django.contrib.auth.decorators import login_required
from djqscsv import render_to_csv_response
from datetime import timedelta
from django.utils import timezone
import logging
logger=logging.getLogger(__name__)

class RecepSignUpView(CreateView):
    """
    Create new Receptionist ids.
    """
    model = User
    form_class = RecepSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'RECEPTIONIST'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        logger.info("New Receptionist Signup")
        return redirect('account_app:dash')

class AdminSignUpView(CreateView):
    """
    Create new Admin ids.
    """
    model = User
    form_class = AdminSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'ADMIN'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        logger.info("New Admin Signup")
        return redirect('account_app:dash')

@admin_required()
def change_password(request):
    """
    Used for changing the password of User.
    """
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            logger.info("Password Changed")
            return redirect('account_app:home')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {
        'form': form
    })

def home(request):
    """
    Render's Home Page.
    """
    logger.info("Home page is opened")
    return render(request, 'home.html')

def about(request):
    """
    Render's About Page.
    """
    logger.info("About page is opened")
    return render(request, 'about.html')

def support(request):
    """
    Render's Support Page.
    """
    logger.info("Support page is opened")
    return render(request, 'support.html')

def team(request):
    """
    Render's Team Page.
    """
    logger.info("Team page is opened")
    return render(request, 'Team.html')

def dashboard(request):
    """
    Render's dashboard Page of admin and receptionist.
    """
    if request.user.is_admin:
        logger.info("Admin Dashboard is opened")
        return render(request, 'admin-dashboard.html')
    if request.user.is_recep:
        logger.info("Receptionist Dashboard is opened")
        return render(request, 'recep-dashboard.html')

def not_found(request):
    """
    If User is not found through Phone No.
    """
    logger.info("search by wrong number")
    return render(request, 'NotFound.html')


@api_view(['GET', 'POST','DELETE'])
def user_list(request):
    """
    List all user details.
    """
    # snippets = Temp.objects.all()   // used in delete request
    if request.method == 'GET':
        snippets = Temp.objects.all()
        serializer = TempSerializer(snippets, many=True)
        print("Get req--")
        logger.info("Api for deatails of visitor is called")
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = TempSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            logger.info("Api for posting deatails of visitor is called")
            return Response(serializer.data, status=201)
        logger.info("Api for posting deatails of visitor is wrong")
        return Response(serializer.errors, status=400)


@api_view(['GET', 'PUT', 'DELETE'])
def user_detail(request, pk):
    """
    Retrieve, update or delete a code snippet.
    """
    try:
        # print(Temp.uid)
        snippet = Temp.objects.get(pk=uid)
    except snippet.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = TempSerializer(snippet)
        return Response(serializer.data)

    elif request.method == 'DELETE':
        snippet.delete()
        print("Deleted---\n")
        return HttpResponse(status=204)


# @admin_required
class HomePageView(TemplateView):
    logger.info("Generate Report Page is opened")
    template_name = 'search.html'


# @admin_required
# Q(name__startswith=query) orQ(date__gte=query2, date__lt=query5)
class SearchResultsView(ListView):
    model = Visitor_perma
    template_name = 'search_result.html'

    def get_queryset(self):
        query  =self.request.GET.get('name')
        query2 =self.request.GET.get('dat1')
        query3 = timezone.now().date() - timedelta(days=8)
        query4 = timezone.now().date() - timedelta(days=15)
        query5 =self.request.GET.get('dat2')
        print(query)
        if query=="":
            qu =Visitor_perma.objects.filter(Q(name__iexact=query) | Q(date__gte=query2, date__lt=query5))
            logger.info("Report Generated by date of visitors.")
        else:
            qu =Visitor_perma.objects.filter(Q(name__iexact=query) & Q(date__gte=query2, date__lt=query5))
            logger.info("Report Generated by name and date both of visitors.")
        return qu

def csv_view(request):
    qu = Visitor_perma.objects.all()
    logger.info("Download the data of all Visitors")
    return render_to_csv_response(qu)

@recep_required
def display(request):
    instance = Temp.objects.all().last()
    form = FilterForm(request.POST or None,instance=instance)
    if request.method == 'POST':
        if form.is_valid():
            visit= form.save(commit=False)
            visit1 = Visitor_perma(name=form.cleaned_data['name'],pincode=form.cleaned_data['pincode'],phone=form.cleaned_data['phone'],dob=form.cleaned_data['dob'], uid=form.cleaned_data['uid'], address=form.cleaned_data['address'],purpose=form.cleaned_data['purpose'])
            visit1.save()
            visit.save()
            logger.info("Form is saved of "+form.cleaned_data['name']+".")
        return redirect('account_app:dash')
    return render(request,'home2.html',{'form':form})

@recep_required
def get_queryset2(request):
    query = request.GET.get('q')
    print(query)
    instance = Visitor_perma.objects.filter(phone=query).last()
    if instance==None:
        return redirect('account_app:not_found')
    form = FilterForm(request.POST or None ,instance =instance)
    if request.method =='POST':
        if form.is_valid():
            visit= form.save(commit=False)
            visit1 = Visitor_perma(name=form.cleaned_data['name'],pincode=form.cleaned_data['pincode'],dob=form.cleaned_data['dob'], date=form.cleaned_data['date'], uid=form.cleaned_data['uid'], address=form.cleaned_data['address'],purpose=form.cleaned_data['purpose'],whoto=form.cleaned_data['whoto'],email=form.cleaned_data['email'],phone=form.cleaned_data['phone'])
            visit1.save()
            visit.save()
            logger.info("Visitor Registration done.")
            return redirect('account_app:dash')
        else:
            print(form.errors)
    return render(request,'search2.html',{'form':form})

@recep_required
def main(request):
    return render(request,'main.html')

# @recep_required
class HomePage2View(TemplateView):
    template_name = 'home1.html'

account/templates/admin-dashboard.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'account/admin-dashboard.css' %}" type="text/css"/>
        <style>
        .header{
          overflow: hidden;
        }
        </style>
        <title>Admin Dashboard</title>
    </head>
    <body>

     <div class="header">
      <div class="inner_header">
        <div class="logo">
          <img src="{% static 'account/logo1.png' %}" height="135">
      </div>
      {% if not user.is_authenticated %}
      <div class="login">
          <a href="{% url 'login' %}"><li>Login</li></a>
      </div>
      {% else %}
      <div class="login">
          <a href="{% url 'logout' %}"><li>Logout</li></a>
      </div>
      {% endif %}
      <div class="innerhead">
        <ul class="nav">
          <a href="{% url 'account_app:home' %}"><li>Home</li></a>
          <a href="{% url 'account_app:about' %}"><li>About us</li></a>
          <a href="{% url 'account_app:support' %}"><li>Support</li></a>
        </ul>
        </div>
        </div>
     </div>
     <div class="container">
       <div id="images" class="splitleft">

          <p class="dash">DASHBOARD</p>
          <img src="{% static 'account/statistics.png' %}"><button class="btn" style="color: rgb(99, 98, 98)"><a href="{% url 'account_app:search' %}"><b><h3>Generate Report</h3></b></a></button><br>
          <img src="{% static 'account/key-silhouette-security-tool-interface-symbol-of-password.png' %}"><button class="btn" style="color: rgb(99, 98, 98)"><a href="{% url 'account_app:admin_signup' %}"><b><h3>Crerate New Admin</b></a></h3></button><br>
          <img src="{% static 'account/new-user.png' %}"><button class="btn" style="color: rgb(99, 98, 98)"><a href="{% url 'account_app:recep_signup' %}"><b><h3>Create New Receptionist</b></h3></a></button><br>
          <img src="{% static 'account/lock.png' %}"><button class="btn" style="color: rgb(99, 98, 98)"><a href="{% url 'account_app:change_password' %}"><b><h3>Change Password</b></h3></a></button><br>
      </div>
      <div class="splitright">
          <img src="{% static 'account/Group32.png' %}" alt="no bg" width="100%" height="90%">
          <h2 class="para">Welcome to Admin Dashboard</h2>
      </div>
     </div>
    </body>
</html>

account/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'landing_asset/landing_page.css' %}" type="text/css"/>
        <link rel="stylesheet" href="https://use.typekit.net/ibt0unw.css">
        <title>Front Desk Assistant</title>
    </head>
    <body>
      <div class="wrapper">
        <div class="main">
          <div class="header">
            <div class="inner_header">
              <div class="logo">
                <img src="logo1.png" height="135">
              </div>
              <div class="logo">
                  <img src="{% static 'account/logo1.png' %}" height="135">
              </div>
              {% if not user.is_authenticated %}
              <div class="login">
                  <a href="{% url 'login' %}"><li>Login</li></a>
              </div>
              {% else %}
              <div class="login">
                  <a href="{% url 'logout' %}"><li>Logout</li></a>
              </div>
              {% endif %}
              <div class="innerhead">
                <ul class="nav">
                  <a href="{% url 'account_app:home' %}"><li>Home</li></a>
                  <a href="{% url 'account_app:about' %}"><li>About us</li></a>
                  <a href="{% url 'account_app:support' %}"><li>Support</li></a>
                </ul>
              </div>
            </div>
          </div>
         </div>
         <div class="scene">
           <img src="{% static 'landing_asset/bg.png' %}" alt="">
           <div class="box">
             <h1>Front Disk Assistant</h1>
             <h3>An automated Visitor Management System</h3>
             <p>With NEC's Front Desk Assistant, visitor check-ins become fully automated and totally transparent</p>
            <button type="button"><a href="{% url 'account_app:display' %}">Register</a></button>
           </div>
         </div>
         <div class="footer">
           <div class="content">
             <div id="contact-info">
               <h5>Contact us</h5>
               <h5>Office</h5>
               <p>Campus-1, 19th KM stone, NH 24, Ghaziabad, <br>Uttar Pradesh 201009 <br>Phone: 1234567890 </p>
               <h5>E-mail</h5>
               <p>wecare@necti.com</p>
             </div>
           </div>
           <div class="content">
             <div id="contact-info">
               <h5><a href="{% url 'account_app:team' %}">Our team</a></h5>
               <h5>f.a.q.</h5>
               <p>How to buy the product?</p>
               <p>Where to buy?</p>
             </div>
           </div>
           <div class="content">
             <div id="contact-info">
               <h5>Follow us</h5>
                <a class="smlogo" href="https://www.instagram.com/"><img src="{% static 'landing_asset/insta_logo.png' %}" alt=""></a>
                <a class="smlogo" href="https://www.facebook.com/"><img src="{% static 'landing_asset/fb_logo.png' %}" alt=""></a>
                <a class="smlogo" href="https://www.twitter.com/"><img src="{% static 'landing_asset/twitter_logo.png' %}" alt=""></a>
             </div>
           </div>
         </div>
         <div class="last-div">
           <div id="left-div">
             <ul>
               <li>Privacy policy</li>
               <li>Terms of services</li>
             </ul>
           </div>
           <div id="right-div">
             <p>&copy WWW.NECTI.COM ALL RIGHT RESERVED</p>
           </div>
         </div>


       </div>
    </body>
</html>

account/templates/home1.html
{% load static %}
 <!DOCTYPE html>
  <html lang="en">
      <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta http-equiv="X-UA-Compatible" content="ie=edge" />
          <link href="https://fonts.googleapis.com/css?family=Open+Sans:600&display=swap" rel="stylesheet">
          <title>Search</title>
          <style >
          	* {
    margin: 0;
    padding: 0;
    list-style: none;
    text-decoration: none;
    box-sizing: border-box;
}

html {
    background: url({% static 'account/temp.png' %}) no-repeat center center fixed;
    background-size: cover;
    height: 100%;
    overflow: hidden;
  }


.header{
    width: 100%;
    height: 80px;
    display: block;
    background:white;
    box-shadow: 0px 0px 10px 0px #ADADAD;
    overflow: auto;
}

.login{
    font-family: 'Open Sans', sans-serif;
    font-size: 12px;
    height: 100%;
    display: table-cell;
    float: right;
    color: #008AF3;
    padding-top: 3%;
    padding-right: 4%;
}

.login a{
    display: table;
    float: right;
    vertical-align: middle;
}

.inner_header{
    width: 1060px;
    height: 100%;
    display: block;
    margin: 0 auto;
}

.innerhead{
    width:750px;
    height: 100%;
    display: block;
    margin: 0 auto;
}

.logo {
    height: 100%;
    display: table-cell;
    float: left;
    vertical-align: middle;
}

.logo img{
    position: absolute;
    margin-top: -25px;
    margin-left: -40px;
}
.nav{
    float: right;
    height: 100%;
    justify-content: space-around;
    align-items: center;
    margin-left: auto;
}

.nav a{
    height: 100%;
    display: table;
    float: left;
    padding: 0px 25px 0px;
    text-align: center;
}

.nav a li{
    display: table-cell;
    vertical-align: middle;
    height: 100%;
    color: #353535;
    font-family: 'Open Sans', sans-serif;
    font-size: 16px;
}
.nav a:last-child{
    padding-right: 80px;
}

.loginbox{
    border-radius: 10px;
    width: 430px;
    height: 440px;
    background-color: white;
    position: relative;
    top: 90px;
    left: 450px;
	margin-bottom:190px;
	margin-top: -50px;
}

.loginheader{
    border-radius: 10px 10px 0px 0px;
    color: white;
    width: 100%;
    height: 35px;
    background-color: black;
    text-align: center;
    text-emphasis-color: white;

}

.mainlogin{
    padding: 25px 40px;
    margin: 0px;
}

#adm{
    padding: 7px;
}

.mainlogin input[type="submit"]
{
    border-radius: 3px;
	border:none;
    margin: 1px 140px;
    color: white;
    background-color: #0006ffba;
    width: 90px;
    height: 25px;
}
 @media screen and (min-width:1600px)
 {

	 .loginbox{
    border-radius: 10px;
    width: 430px;
    height: 440px;
    background-color: white;
    position: relative;
    top: 150px;
    left: 750px;
	margin-bottom:190px;
	margin-top: -50px;
}

 }
  </style>
      </head>
      <body>

       <div class="header">
        <div class="inner_header">
          <div class="logo">
              <img src="{% static 'account/logo1.png' %}" height="135">
          </div>
          {% if not user.is_authenticated %}
          <div class="login">
              <a href="{% url 'login' %}"><li>Login</li></a>
          </div>
          {% else %}
          <div class="login">
              <a href="{% url 'logout' %}"><li>Logout</li></a>
          </div>
          {% endif %}
          <div class="innerhead">
            <ul class="nav">
              <a href="{% url 'account_app:home' %}"><li>Home</li></a>
              <a href="{% url 'account_app:about' %}"><li>About us</li></a>
              <a href="{% url 'account_app:support' %}"><li>Support</li></a>
            </ul>
          </div>
          </div>
       </div>
        <div class="loginbox">
          <div class="loginheader">
             <p id="adm">SEARCH</p>
          </div>
          <div class="mainlogin">


<form action="{% url 'account_app:search_results' %}" method="get">
  <input name="q" type="text" placeholder="Search..."style="margin: 0px 0px 20px 97px; height:22px;  width: 200px; border-radius: 3px; border:none; background-color:#D3D3D3;">
</form>
</div>
</div>
</body>
</html>

account/templates/main.html
<a href="{% url 'account_app:vhome' %}"><button>SEARCH</button></a>
<a href="{% url 'account_app:display' %}"><button>REGISTER</button></a>

account/templates/search.html
<!DOCTYPE html>
  <html lang="en">
	{% load static %}
      <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta http-equiv="X-UA-Compatible" content="ie=edge" />
          <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&display=swap" rel="stylesheet">
          <title>Generate Report</title>
          <style>
          		* {
    margin: 0;
    padding: 0;
    list-style: none;
    text-decoration: none;
    box-sizing: border-box;
}

html {
    background: url({% static "account/temp.png" %}) no-repeat center center fixed;
    background-size: cover;
    height: 100%;
    overflow: hidden;
  }

.header{
    width: 100%;
    height: 80px;
    display: block;
    background:white;
    box-shadow: 0px 0px 10px 0px #ADADAD;
    overflow: auto;
}

.login{
    font-family: 'Open Sans', sans-serif;
    font-size: 12px;
    height: 100%;
    display: table-cell;
    float: right;
    color: #008AF3;
    padding-top: 3%;
    padding-right: 4%;
}

.login a{
    display: table;
    float: right;
    vertical-align: middle;
}

.inner_header{
    width: 1060px;
    height: 100%;
    display: block;
    margin: 0 auto;
}

.innerhead{
    width:750px;
    height: 100%;
    display: block;
    margin: 0 auto;
}

.logo {
    height: 100%;
    display: table-cell;
    float: left;
    vertical-align: middle;
}

.logo img{
    position: absolute;
    margin-top: -25px;
    margin-left: -40px;
}
.nav{
    float: right;
    height: 100%;
    justify-content: space-around;
    align-items: center;
    margin-left: auto;
}

.nav a{
    height: 100%;
    display: table;
    float: left;
    padding: 0px 25px 0px;
    text-align: center;
}

.nav a li{
    display: table-cell;
    vertical-align: middle;
    height: 100%;
    color: #353535;
    font-family: 'Open Sans', sans-serif;
    font-size: 16px;
    font-weight: 600;
}
.nav a:last-child{
    padding-right: 80px;
}


.container{
    background: #fff;
    width: 500px;
    height: 400px;
    border-radius: 12px;
    margin: 0 auto;
    margin-top: 50px;
}

.para{
    background-color: #1E1E1E;
    color: white;
    font-family: 'Courier New', Courier, monospace;
    text-align: center;
    border-top-left-radius: 12px;
    border-top-right-radius: 12px;
    padding: 15px 0px 15px 0px;
    margin-bottom: 50px;
    font-family: 'Open Sans', sans-serif;
    font-size: 20px;
    height: 58px;
}



.lables{
    display: block;
    margin-left: 20px;
    margin-right: 50px;

    color: #2C2C2C;
    font-family: 'Open Sans', sans-serif;
    font-size: 15px;
    padding: 5px 0 0 0;
    display: inline-block;
    text-align: right;
    line-height: 20px;
}

.table{
   margin: 0px auto;

}
.input{
    padding: 20px;
}

input[type=date]{
  float: left;
  width: 280px;
  padding: 10px;
  margin: 10px;
  display: block;
  border-radius: 6px;
  border: none;
  background-color: #E5E5E5;

}

input[type=text],input[type=number]{
    float: right;
    width: 280px;
    padding: 10px;
    margin: 10px;
    display: block;
    border-radius: 6px;
    border: none;
    background-color: #E5E5E5;

}

input[type=submit]{
    position: absolute;
    left:45%;
    width: 100px;
    height: 30px;
    border-radius: 6px;
    border: none;
    background-color: #008AF3;
    color: #fff;
    margin: 40px;
}
          </style>
      </head>
      <body>

       <div class="header">
        <div class="inner_header">
					<div class="logo">
	            <img src="{% static 'account/logo1.png' %}" height="135">
	        </div>
          {% if not user.is_authenticated %}
          <div class="login">
              <a href="{% url 'login' %}"><li>Login</li></a>
          </div>
          {% else %}
          <div class="login">
              <a href="{% url 'logout' %}"><li>Logout</li></a>
          </div>
          {% endif %}
	        <div class="innerhead">
	          <ul class="nav">
	            <a href="{% url 'account_app:home' %}"><li>Home</li></a>
	            <a href="{% url 'account_app:about' %}"><li>About us</li></a>
	            <a href="{% url 'account_app:support' %}"><li>Support</li></a>
	          </ul>
          </div>
          </div>
       </div>

       <div class="container">
          <form action="{% url 'account_app:search_result' %}",method="get">
            <p class="para">GENERATE REPORT</p>
            <table class="table">
                <tr class="row">
                    <td>
                        <lable class="lables">Name</lable>
                    </td>
                    <td>
                        <input type="text" class="input" name="name">
                    </td>
                </tr>
                <tr class="row">
                    <td>
                        <lable class="lables">Date</lable>
                    </td>
                    <td style="width:200px;">
                        <input type="date" class="input1" name="dat1" required style="width:130px; float:left;">
                    </td>
                    <td>
                      <input type="date" id="d2" class="input2" name="dat2" required style="width: 130px;
                      right: 150px;
                      position: relative;
                      padding: 10px;
                      margin: 10px;
                      display: block;">

                  </td>
                </tr>
                <tr class="row">
                    <td></td>
                    <td>
                        <input type="submit" class="submit" value="Generate">
                    </td>
                </tr>
            </table>
          </form>
      </div>


      </body>
  </html>